Setting up DB connection
IT19180380/tusk pull request #1
Opened 2020-10-02 10:56 UTC by tharathara

add db connection files

2020-10-02 15:18 UTC, miyurusankalpa requested changes
Please add the index.js as well

2020-10-02 15:18 UTC, miyurusankalpa commented on DBconnection.js
> +        host: '127.0.0.2',
please use env file to enter environment variables

2020-10-02 15:18 UTC, miyurusankalpa commented on package.json
> +  "main": "index.js",
there isnt seem to be a index.js in this repo

2020-10-06 04:33 UTC, tharathara commented
@miyurusankalpa  noted :D thanks

2020-10-06 04:34 UTC, merged